### ISSUE TITLE
Windows - UI stuck after transcribe when using GPU

### ISSUE THREAD

**Issue by fstolba** [JuergenFleiss/aTrain#44] opened 2024-11-30 11:47 UTC
Hi,

Version: Current from Microsoft Store (should be 1.2)
OS: Windows 10 22H2
Input file: m4a file about 12 min. long
GPU: GTX1060

The conversion process gets stuck after the progress bar reaches 100% in the transcribe step. Tried with or without speaker detection, that makes no difference. From Task Manager it seems the application is idle (0% CPU, 0% GPU util). I cancelled the conversion after 15+ minutes of it idling. The log even says conversion finished but there are no output files.

Conversion of the same file works fine when using the CPU instead of the GPU.

Log:
```
[2024-11-30 12-42-30] ------ File ID created: 2411301242-Vorgesp
[2024-11-30 12-42-30] ------ Directory created
[2024-11-30 12-42-31] ------ Audio file loaded and decoded
[2024-11-30 12-42-31] ------ Audio duration calculated
[2024-11-30 12-42-31] ------ Metadata created
[2024-11-30 12-42-34] ------ Model loaded
[2024-11-30 12-42-40] ------ Transcribing with regular model.
[2024-11-30 12-43-38] ------ Transcription successful
```

Metadata file:
```
audio_duration: 712
compute_type: int8
device: cuda
file_id: 2411301242-Vorgesp
filename: 2411301242-Vorgesp
language: null
model: large-v3-turbo
num_speakers: auto-detect
path_to_audio_file: Vorgespraech.m4a
speaker_detection: true
timestamp: 2024-11-30 12-42-30
```

![image](https://github.com/user-attachments/assets/d13da34b-caf1-4b1b-8e4b-3047653016ac)

**Comment by JuergenFleiss** [comment] 2024-12-04 10:33
Thanks, we are looking into it. 

Closed as duplicate of issue https://github.com/JuergenFleiss/aTrain/issues/41.

**Closed by JuergenFleiss** 2024-12-04 10:33 UTC
